# format = """
# $directory\
# $git_branch\
# $fill\
# $python\
# $golang\
# $rlang\
# $jobs\
# $line_break\
# $character"""
#
# # Inserts a blank line between shell prompts
add_newline = false

# # Replace the 'â¯' symbol in the prompt with 'âœ'
# [character] # The name of the module we are configuring is 'character'
# success_symbol = '[âœ](bold green)' # The 'success_symbol' segment is being set to 'âœ' with the color 'bold green'
command_timeout = 1000

# [fill]
# symbol = "_"

[directory]
style = 'bold fg:white'
truncation_length = 2
truncation_symbol = ' ó°–³  â€¦/'


[directory.substitutions]
'Documents' = 'ó°ˆ™'

[python]
style = 'yellow'
#symbol = 'îˆµğŸğŸ'
# format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'
pyenv_version_name = true
pyenv_prefix = ''

[golang]
# style = 'blue'
symbol = 'î˜§ '

[package]
symbol = 'ó°— '

[jobs]
symbol = 'ï€“ '
style = 'red'
number_threshold = 1
format = '[$symbol]($style)'

# ~/.config/starship.toml

[cmd_duration]
disabled = true

